### ISSUE TITLE
I'm having issues using example cmd

### ISSUE THREAD

**Issue by devan-mysterio** [ruffrick/jda-commands#6]
@Command
class Mood : SlashCommand() {
    @Command
    fun mood(event: SlashCommandInteractionEvent) {
        event.reply("How are you?").addActionRow(
            success("good", "Good"), danger("bad", "Bad")
        ).queue()
    }

    @Button
    fun good(event: ButtonInteractionEvent) {
        event.editMessage("That's good to hear!").setActionRow().queue()
    }

    @Button
    fun bad(event: ButtonInteractionEvent) {
        event.editMessage("Oh no! Here, have some \uD83C\uDF68!").setActionRow().queue()
    }
}

java.lang.IllegalArgumentException: Unknown button good
	at dev.ruffrick.jda.commands.event.ButtonInteractionListener.onEvent(ButtonInteractionListener.kt:21)
	at dev.ruffrick.jda.kotlinx.event.SuspendEventManager$handle$1.invokeSuspend(SuspendEventManager.kt:38)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
	
	when I try to click the buttons it does this

**Comment by ruffrick** [comment]
That exception is thrown when the CommandRegistry can't find any command associated with that button. Are you sure you correctly registered and updated the command?

**Comment by devan-mysterio** [comment]
So, how do I correct so

**Comment by ruffrick** [comment]
As the example in the readme states:
```kt
fun main() {
    val jda = JDABuilder.createLight("token")
        .useSuspendEventManager()
        .build()

    val commandRegistry = CommandRegistryBuilder()
        .addCommands(PingCommand(), HelloCommand(), GreetCommand())
        .build()

    commandRegistry.updateCommands(jda)
}
```

**Comment by devan-mysterio** [comment]
val intents: Collection<GatewayIntent> = GatewayIntent.getIntents(GatewayIntent.ALL_INTENTS)
    val shardBuilder = DefaultShardManagerBuilder.createDefault(
        "token", intents
    ).setMemberCachePolicy(MemberCachePolicy.ALL).setChunkingFilter(ChunkingFilter.ALL)
        .setActivity(Activity.watching("for New Shards")).useSuspendEventManager().build()

    val commandRegistry = CommandRegistryBuilder().addCommand(Ping()).build()

    commandRegistry.updateCommands(shardBuilder)
    
    I do have this?

**Comment by devan-mysterio** [comment]
Suggestion this would be easier if you had a support discord or something

**Comment by ruffrick** [comment]
https://discord.gg/Hs4mkEk2
